//
// Created by Marcinek on 08.05.2021.
//

#ifndef ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H
#define ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H


class Menu {
public:
explicit Menu();
void start();
};


#endif //ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H
