
#ifndef ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H
#define ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H


class Menu {
public:
void start();
};


#endif //ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_MENU_H
