
#ifndef ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_TESTS_H
#define ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_TESTS_H


class Tests {
public:
    void test();
};


#endif //ALGORITHMS_KRUSKAL_PRIM_DJKSTRY_BELLMANFORD_TESTS_H
